repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: '^(profiling_results/|\.docker_build/)'
      - id: end-of-file-fixer
        exclude: '^(profiling_results/|\.docker_build/)'
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.8
    hooks:
      - id: clang-format
        files: "\\.(c|cc|cxx|cpp|h|hh|hpp)$"
        exclude: '^(profiling_results/|\.docker_build/)'
